/*
Copyright (c) 2013, Dienst Wegverkeer, RDW, All rights reserved. 

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 

• Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
• Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 
• Neither the name of the Dienst Wegverkeer, RDW,  nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

// <auto-generated />
namespace EVR.ReadVehicleLicenseCardDemo
{
    partial class FormeVRDemo
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormeVRDemo));
            this.pnlForm = new System.Windows.Forms.Panel();
            this.flatTabControl1 = new FlatTabControl.FlatTabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.pnlBack = new System.Windows.Forms.Panel();
            this.registrationCardBack1 = new EVR.ReadVehicleLicenseCardDemo.RegistrationCardBack();
            this.pnlFront = new System.Windows.Forms.Panel();
            this.registrationCardFront1 = new EVR.ReadVehicleLicenseCardDemo.RegistrationCardFront();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.pnlForm.SuspendLayout();
            this.flatTabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.pnlBack.SuspendLayout();
            this.pnlFront.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // pnlForm
            // 
            this.pnlForm.Controls.Add(this.flatTabControl1);
            this.pnlForm.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlForm.Location = new System.Drawing.Point(0, 0);
            this.pnlForm.Name = "pnlForm";
            this.pnlForm.Size = new System.Drawing.Size(604, 782);
            this.pnlForm.TabIndex = 7;
            // 
            // flatTabControl1
            // 
            this.flatTabControl1.Controls.Add(this.tabPage1);
            this.flatTabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.flatTabControl1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.flatTabControl1.Location = new System.Drawing.Point(0, 0);
            this.flatTabControl1.myBackColor = System.Drawing.SystemColors.Control;
            this.flatTabControl1.Name = "flatTabControl1";
            this.flatTabControl1.SelectedIndex = 0;
            this.flatTabControl1.Size = new System.Drawing.Size(604, 782);
            this.flatTabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.pnlBack);
            this.tabPage1.Controls.Add(this.pnlFront);
            this.tabPage1.Controls.Add(this.pictureBox1);
            this.tabPage1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tabPage1.Location = new System.Drawing.Point(4, 25);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(596, 753);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "eVR";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // pnlBack
            // 
            this.pnlBack.Controls.Add(this.registrationCardBack1);
            this.pnlBack.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlBack.Location = new System.Drawing.Point(3, 377);
            this.pnlBack.Name = "pnlBack";
            this.pnlBack.Size = new System.Drawing.Size(590, 373);
            this.pnlBack.TabIndex = 2;
            // 
            // registrationCardBack1
            // 
            this.registrationCardBack1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("registrationCardBack1.BackgroundImage")));
            this.registrationCardBack1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.registrationCardBack1.Data = null;
            this.registrationCardBack1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.registrationCardBack1.Location = new System.Drawing.Point(0, 0);
            this.registrationCardBack1.Name = "registrationCardBack1";
            this.registrationCardBack1.Size = new System.Drawing.Size(590, 373);
            this.registrationCardBack1.TabIndex = 0;
            // 
            // pnlFront
            // 
            this.pnlFront.Controls.Add(this.registrationCardFront1);
            this.pnlFront.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlFront.Location = new System.Drawing.Point(3, 3);
            this.pnlFront.Name = "pnlFront";
            this.pnlFront.Size = new System.Drawing.Size(590, 374);
            this.pnlFront.TabIndex = 1;
            // 
            // registrationCardFront1
            // 
            this.registrationCardFront1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("registrationCardFront1.BackgroundImage")));
            this.registrationCardFront1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.registrationCardFront1.Data = null;
            this.registrationCardFront1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.registrationCardFront1.ImeMode = System.Windows.Forms.ImeMode.Hiragana;
            this.registrationCardFront1.Location = new System.Drawing.Point(0, 0);
            this.registrationCardFront1.Name = "registrationCardFront1";
            this.registrationCardFront1.Size = new System.Drawing.Size(590, 374);
            this.registrationCardFront1.TabIndex = 0;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(100, 50);
            this.pictureBox1.TabIndex = 3;
            this.pictureBox1.TabStop = false;
            // 
            // frmeVRDemo
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(604, 782);
            this.Controls.Add(this.pnlForm);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmeVRDemo";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Demo Tool - View Electronic Vehicle Registration information from the smartcard";
            //this.Load += new System.EventHandler(this.frmeVRDemo_Load);
            this.pnlForm.ResumeLayout(false);
            this.flatTabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.pnlBack.ResumeLayout(false);
            this.pnlFront.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnlForm;
        private FlatTabControl.FlatTabControl flatTabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.Panel pnlBack;
        private RegistrationCardBack registrationCardBack1;
        private System.Windows.Forms.Panel pnlFront;
        private RegistrationCardFront registrationCardFront1;
        private System.Windows.Forms.PictureBox pictureBox1;
    }
}

