/*
Copyright (c) 2013, Dienst Wegverkeer, RDW, All rights reserved. 

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 

• Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
• Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 
• Neither the name of the Dienst Wegverkeer, RDW,  nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

// <auto-generated />
namespace EVR.ReadVehicleLicenseCardDemo
{
    partial class RegistrationCardFront
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnleVR = new System.Windows.Forms.Panel();
            this.lblI = new System.Windows.Forms.Label();
            this.lblC13_2 = new System.Windows.Forms.Label();
            this.lblC11_2 = new System.Windows.Forms.Label();
            this.lblDocumentnummer = new System.Windows.Forms.Label();
            this.lblC13_1 = new System.Windows.Forms.Label();
            this.lblC12 = new System.Windows.Forms.Label();
            this.lblC11_1 = new System.Windows.Forms.Label();
            this.lblB2 = new System.Windows.Forms.Label();
            this.lblB1 = new System.Windows.Forms.Label();
            this.lblMeldcode = new System.Windows.Forms.Label();
            this.lblA = new System.Windows.Forms.Label();
            this.pnleVR.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnleVR
            // 
            this.pnleVR.BackColor = System.Drawing.Color.Transparent;
            this.pnleVR.Controls.Add(this.lblI);
            this.pnleVR.Controls.Add(this.lblC13_2);
            this.pnleVR.Controls.Add(this.lblC11_2);
            this.pnleVR.Controls.Add(this.lblDocumentnummer);
            this.pnleVR.Controls.Add(this.lblC13_1);
            this.pnleVR.Controls.Add(this.lblC12);
            this.pnleVR.Controls.Add(this.lblC11_1);
            this.pnleVR.Controls.Add(this.lblB2);
            this.pnleVR.Controls.Add(this.lblB1);
            this.pnleVR.Controls.Add(this.lblMeldcode);
            this.pnleVR.Controls.Add(this.lblA);
            this.pnleVR.Location = new System.Drawing.Point(184, 101);
            this.pnleVR.Name = "pnleVR";
            this.pnleVR.Size = new System.Drawing.Size(394, 266);
            this.pnleVR.TabIndex = 2;
            // 
            // lblI
            // 
            this.lblI.AutoSize = true;
            this.lblI.BackColor = System.Drawing.Color.Transparent;
            this.lblI.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblI.Location = new System.Drawing.Point(4, 81);
            this.lblI.Name = "lblI";
            this.lblI.Size = new System.Drawing.Size(77, 15);
            this.lblI.TabIndex = 29;
            this.lblI.Text = "1234567890";
            // 
            // lblC13_2
            // 
            this.lblC13_2.AutoSize = true;
            this.lblC13_2.BackColor = System.Drawing.Color.Transparent;
            this.lblC13_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblC13_2.Location = new System.Drawing.Point(4, 177);
            this.lblC13_2.Name = "lblC13_2";
            this.lblC13_2.Size = new System.Drawing.Size(287, 15);
            this.lblC13_2.TabIndex = 28;
            this.lblC13_2.Text = "1234567890123456789012345678901234567890";
            // 
            // lblC11_2
            // 
            this.lblC11_2.AutoSize = true;
            this.lblC11_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblC11_2.Location = new System.Drawing.Point(3, 120);
            this.lblC11_2.Name = "lblC11_2";
            this.lblC11_2.Size = new System.Drawing.Size(315, 20);
            this.lblC11_2.TabIndex = 27;
            this.lblC11_2.Text = "Oldenbarneveld Oetgens van Waveren";
            // 
            // lblDocumentnummer
            // 
            this.lblDocumentnummer.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.lblDocumentnummer.AutoSize = true;
            this.lblDocumentnummer.BackColor = System.Drawing.Color.Transparent;
            this.lblDocumentnummer.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDocumentnummer.Location = new System.Drawing.Point(219, 235);
            this.lblDocumentnummer.Name = "lblDocumentnummer";
            this.lblDocumentnummer.Size = new System.Drawing.Size(99, 20);
            this.lblDocumentnummer.TabIndex = 26;
            this.lblDocumentnummer.Text = "1234567890";
            this.lblDocumentnummer.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // lblC13_1
            // 
            this.lblC13_1.AutoSize = true;
            this.lblC13_1.BackColor = System.Drawing.Color.Transparent;
            this.lblC13_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblC13_1.Location = new System.Drawing.Point(4, 159);
            this.lblC13_1.Name = "lblC13_1";
            this.lblC13_1.Size = new System.Drawing.Size(287, 15);
            this.lblC13_1.TabIndex = 19;
            this.lblC13_1.Text = "1234567890123456789012345678901234567890";
            // 
            // lblC12
            // 
            this.lblC12.AutoSize = true;
            this.lblC12.BackColor = System.Drawing.Color.Transparent;
            this.lblC12.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblC12.Location = new System.Drawing.Point(3, 140);
            this.lblC12.Name = "lblC12";
            this.lblC12.Size = new System.Drawing.Size(77, 15);
            this.lblC12.TabIndex = 16;
            this.lblC12.Text = "1234567890";
            // 
            // lblC11_1
            // 
            this.lblC11_1.AutoSize = true;
            this.lblC11_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblC11_1.Location = new System.Drawing.Point(3, 99);
            this.lblC11_1.Name = "lblC11_1";
            this.lblC11_1.Size = new System.Drawing.Size(315, 20);
            this.lblC11_1.TabIndex = 14;
            this.lblC11_1.Text = "Oldenbarneveld Oetgens van Waveren";
            // 
            // lblB2
            // 
            this.lblB2.AutoSize = true;
            this.lblB2.BackColor = System.Drawing.Color.Transparent;
            this.lblB2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblB2.Location = new System.Drawing.Point(3, 63);
            this.lblB2.Name = "lblB2";
            this.lblB2.Size = new System.Drawing.Size(77, 15);
            this.lblB2.TabIndex = 12;
            this.lblB2.Text = "1234567890";
            // 
            // lblB1
            // 
            this.lblB1.AutoSize = true;
            this.lblB1.BackColor = System.Drawing.Color.Transparent;
            this.lblB1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblB1.Location = new System.Drawing.Point(3, 45);
            this.lblB1.Name = "lblB1";
            this.lblB1.Size = new System.Drawing.Size(77, 15);
            this.lblB1.TabIndex = 11;
            this.lblB1.Text = "1234567890";
            // 
            // lblMeldcode
            // 
            this.lblMeldcode.AutoSize = true;
            this.lblMeldcode.BackColor = System.Drawing.Color.Transparent;
            this.lblMeldcode.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMeldcode.Location = new System.Drawing.Point(3, 24);
            this.lblMeldcode.Name = "lblMeldcode";
            this.lblMeldcode.Size = new System.Drawing.Size(39, 15);
            this.lblMeldcode.TabIndex = 8;
            this.lblMeldcode.Text = "1234";
            // 
            // lblA
            // 
            this.lblA.AutoSize = true;
            this.lblA.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblA.Location = new System.Drawing.Point(3, 3);
            this.lblA.Name = "lblA";
            this.lblA.Size = new System.Drawing.Size(93, 20);
            this.lblA.TabIndex = 6;
            this.lblA.Text = "00-RDW-0";
            // 
            // RegistrationCardFront
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::EVR.ReadVehicleLicenseCardDemo.Properties.Resources.kentekenbewijs_vk_new;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Controls.Add(this.pnleVR);
            this.DoubleBuffered = true;
            this.Name = "RegistrationCardFront";
            this.Size = new System.Drawing.Size(586, 370);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.RegistrationCardFront_Paint);
            this.pnleVR.ResumeLayout(false);
            this.pnleVR.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnleVR;
        private System.Windows.Forms.Label lblDocumentnummer;
        private System.Windows.Forms.Label lblC13_1;
        private System.Windows.Forms.Label lblC12;
        private System.Windows.Forms.Label lblC11_1;
        private System.Windows.Forms.Label lblB2;
        private System.Windows.Forms.Label lblB1;
        private System.Windows.Forms.Label lblMeldcode;
        private System.Windows.Forms.Label lblA;
        private System.Windows.Forms.Label lblC11_2;
        private System.Windows.Forms.Label lblC13_2;
        private System.Windows.Forms.Label lblI;

    }
}
