/*
Copyright (c) 2013, Dienst Wegverkeer, RDW, All rights reserved. 

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 

• Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. 
• Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. 
• Neither the name of the Dienst Wegverkeer, RDW,  nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

// <auto-generated />
namespace EVR.ReadVehicleLicenseCardDemo
{
    partial class RegistrationCardBack
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.pnleVRBack = new System.Windows.Forms.Panel();
            this.lblS2 = new System.Windows.Forms.Label();
            this.lblS1 = new System.Windows.Forms.Label();
            this.lblT = new System.Windows.Forms.Label();
            this.lblG = new System.Windows.Forms.Label();
            this.lblO2 = new System.Windows.Forms.Label();
            this.lblO1 = new System.Windows.Forms.Label();
            this.lblQ = new System.Windows.Forms.Label();
            this.lblP3 = new System.Windows.Forms.Label();
            this.lblP2 = new System.Windows.Forms.Label();
            this.lblP1 = new System.Windows.Forms.Label();
            this.lblF3 = new System.Windows.Forms.Label();
            this.lblF2 = new System.Windows.Forms.Label();
            this.lblF1 = new System.Windows.Forms.Label();
            this.lblV9 = new System.Windows.Forms.Label();
            this.lblK = new System.Windows.Forms.Label();
            this.lblR = new System.Windows.Forms.Label();
            this.lblD3_2 = new System.Windows.Forms.Label();
            this.lblD3_1 = new System.Windows.Forms.Label();
            this.lblD2_3 = new System.Windows.Forms.Label();
            this.lblD2_2 = new System.Windows.Forms.Label();
            this.lblD2_1 = new System.Windows.Forms.Label();
            this.lblJ = new System.Windows.Forms.Label();
            this.lblD1 = new System.Windows.Forms.Label();
            this.lblE = new System.Windows.Forms.Label();
            this.pnleVRBack.SuspendLayout();
            this.SuspendLayout();
            // 
            // pnleVRBack
            // 
            this.pnleVRBack.BackColor = System.Drawing.Color.Transparent;
            this.pnleVRBack.Controls.Add(this.lblS2);
            this.pnleVRBack.Controls.Add(this.lblS1);
            this.pnleVRBack.Controls.Add(this.lblT);
            this.pnleVRBack.Controls.Add(this.lblG);
            this.pnleVRBack.Controls.Add(this.lblO2);
            this.pnleVRBack.Controls.Add(this.lblO1);
            this.pnleVRBack.Controls.Add(this.lblQ);
            this.pnleVRBack.Controls.Add(this.lblP3);
            this.pnleVRBack.Controls.Add(this.lblP2);
            this.pnleVRBack.Controls.Add(this.lblP1);
            this.pnleVRBack.Controls.Add(this.lblF3);
            this.pnleVRBack.Controls.Add(this.lblF2);
            this.pnleVRBack.Controls.Add(this.lblF1);
            this.pnleVRBack.Controls.Add(this.lblV9);
            this.pnleVRBack.Controls.Add(this.lblK);
            this.pnleVRBack.Controls.Add(this.lblR);
            this.pnleVRBack.Controls.Add(this.lblD3_2);
            this.pnleVRBack.Controls.Add(this.lblD3_1);
            this.pnleVRBack.Controls.Add(this.lblD2_3);
            this.pnleVRBack.Controls.Add(this.lblD2_2);
            this.pnleVRBack.Controls.Add(this.lblD2_1);
            this.pnleVRBack.Controls.Add(this.lblJ);
            this.pnleVRBack.Controls.Add(this.lblD1);
            this.pnleVRBack.Controls.Add(this.lblE);
            this.pnleVRBack.Location = new System.Drawing.Point(195, 14);
            this.pnleVRBack.Name = "pnleVRBack";
            this.pnleVRBack.Size = new System.Drawing.Size(349, 345);
            this.pnleVRBack.TabIndex = 0;
            // 
            // lblS2
            // 
            this.lblS2.AutoSize = true;
            this.lblS2.BackColor = System.Drawing.Color.Transparent;
            this.lblS2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblS2.Location = new System.Drawing.Point(235, 248);
            this.lblS2.Name = "lblS2";
            this.lblS2.Size = new System.Drawing.Size(19, 13);
            this.lblS2.TabIndex = 97;
            this.lblS2.Text = "12";
            // 
            // lblS1
            // 
            this.lblS1.AutoSize = true;
            this.lblS1.BackColor = System.Drawing.Color.Transparent;
            this.lblS1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblS1.Location = new System.Drawing.Point(235, 231);
            this.lblS1.Name = "lblS1";
            this.lblS1.Size = new System.Drawing.Size(19, 13);
            this.lblS1.TabIndex = 96;
            this.lblS1.Text = "12";
            // 
            // lblT
            // 
            this.lblT.AutoSize = true;
            this.lblT.BackColor = System.Drawing.Color.Transparent;
            this.lblT.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblT.Location = new System.Drawing.Point(235, 214);
            this.lblT.Name = "lblT";
            this.lblT.Size = new System.Drawing.Size(53, 13);
            this.lblT.TabIndex = 95;
            this.lblT.Text = "123 km/h";
            // 
            // lblG
            // 
            this.lblG.AutoSize = true;
            this.lblG.BackColor = System.Drawing.Color.Transparent;
            this.lblG.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblG.Location = new System.Drawing.Point(235, 195);
            this.lblG.Name = "lblG";
            this.lblG.Size = new System.Drawing.Size(58, 13);
            this.lblG.TabIndex = 94;
            this.lblG.Text = "123456 kg";
            // 
            // lblO2
            // 
            this.lblO2.AutoSize = true;
            this.lblO2.BackColor = System.Drawing.Color.Transparent;
            this.lblO2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblO2.Location = new System.Drawing.Point(6, 326);
            this.lblO2.Name = "lblO2";
            this.lblO2.Size = new System.Drawing.Size(67, 13);
            this.lblO2.TabIndex = 93;
            this.lblO2.Text = "123456 kg";
            // 
            // lblO1
            // 
            this.lblO1.AutoSize = true;
            this.lblO1.BackColor = System.Drawing.Color.Transparent;
            this.lblO1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblO1.Location = new System.Drawing.Point(6, 309);
            this.lblO1.Name = "lblO1";
            this.lblO1.Size = new System.Drawing.Size(67, 13);
            this.lblO1.TabIndex = 92;
            this.lblO1.Text = "123456 kg";
            // 
            // lblQ
            // 
            this.lblQ.AutoSize = true;
            this.lblQ.BackColor = System.Drawing.Color.Transparent;
            this.lblQ.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblQ.Location = new System.Drawing.Point(6, 293);
            this.lblQ.Name = "lblQ";
            this.lblQ.Size = new System.Drawing.Size(80, 13);
            this.lblQ.TabIndex = 91;
            this.lblQ.Text = "123456 kW/kg";
            // 
            // lblP3
            // 
            this.lblP3.AutoSize = true;
            this.lblP3.BackColor = System.Drawing.Color.Transparent;
            this.lblP3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblP3.Location = new System.Drawing.Point(6, 278);
            this.lblP3.Name = "lblP3";
            this.lblP3.Size = new System.Drawing.Size(43, 13);
            this.lblP3.TabIndex = 90;
            this.lblP3.Text = "123456";
            // 
            // lblP2
            // 
            this.lblP2.AutoSize = true;
            this.lblP2.BackColor = System.Drawing.Color.Transparent;
            this.lblP2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblP2.Location = new System.Drawing.Point(6, 261);
            this.lblP2.Name = "lblP2";
            this.lblP2.Size = new System.Drawing.Size(45, 13);
            this.lblP2.TabIndex = 89;
            this.lblP2.Text = "123 kW";
            // 
            // lblP1
            // 
            this.lblP1.AutoSize = true;
            this.lblP1.BackColor = System.Drawing.Color.Transparent;
            this.lblP1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblP1.Location = new System.Drawing.Point(6, 244);
            this.lblP1.Name = "lblP1";
            this.lblP1.Size = new System.Drawing.Size(66, 13);
            this.lblP1.TabIndex = 88;
            this.lblP1.Text = "123456 cm3";
            // 
            // lblF3
            // 
            this.lblF3.AutoSize = true;
            this.lblF3.BackColor = System.Drawing.Color.Transparent;
            this.lblF3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblF3.Location = new System.Drawing.Point(6, 227);
            this.lblF3.Name = "lblF3";
            this.lblF3.Size = new System.Drawing.Size(58, 13);
            this.lblF3.TabIndex = 87;
            this.lblF3.Text = "123456 kg";
            // 
            // lblF2
            // 
            this.lblF2.AutoSize = true;
            this.lblF2.BackColor = System.Drawing.Color.Transparent;
            this.lblF2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblF2.Location = new System.Drawing.Point(6, 212);
            this.lblF2.Name = "lblF2";
            this.lblF2.Size = new System.Drawing.Size(58, 13);
            this.lblF2.TabIndex = 86;
            this.lblF2.Text = "123456 kg";
            // 
            // lblF1
            // 
            this.lblF1.AutoSize = true;
            this.lblF1.BackColor = System.Drawing.Color.Transparent;
            this.lblF1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblF1.Location = new System.Drawing.Point(6, 194);
            this.lblF1.Name = "lblF1";
            this.lblF1.Size = new System.Drawing.Size(58, 13);
            this.lblF1.TabIndex = 85;
            this.lblF1.Text = "123456 kg";
            // 
            // lblV9
            // 
            this.lblV9.AutoSize = true;
            this.lblV9.BackColor = System.Drawing.Color.Transparent;
            this.lblV9.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblV9.Location = new System.Drawing.Point(6, 178);
            this.lblV9.Name = "lblV9";
            this.lblV9.Size = new System.Drawing.Size(145, 13);
            this.lblV9.TabIndex = 84;
            this.lblV9.Text = "12345678901234567890123";
            // 
            // lblK
            // 
            this.lblK.AutoSize = true;
            this.lblK.BackColor = System.Drawing.Color.Transparent;
            this.lblK.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblK.Location = new System.Drawing.Point(6, 162);
            this.lblK.Name = "lblK";
            this.lblK.Size = new System.Drawing.Size(217, 13);
            this.lblK.TabIndex = 83;
            this.lblK.Text = "12345678901234567890123456789012345";
            // 
            // lblR
            // 
            this.lblR.AutoSize = true;
            this.lblR.BackColor = System.Drawing.Color.Transparent;
            this.lblR.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblR.Location = new System.Drawing.Point(6, 146);
            this.lblR.Name = "lblR";
            this.lblR.Size = new System.Drawing.Size(85, 13);
            this.lblR.TabIndex = 82;
            this.lblR.Text = "1234567890123";
            // 
            // lblD3_2
            // 
            this.lblD3_2.AutoSize = true;
            this.lblD3_2.BackColor = System.Drawing.Color.Transparent;
            this.lblD3_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD3_2.Location = new System.Drawing.Point(6, 128);
            this.lblD3_2.Name = "lblD3_2";
            this.lblD3_2.Size = new System.Drawing.Size(67, 13);
            this.lblD3_2.TabIndex = 81;
            this.lblD3_2.Text = "1234567890";
            // 
            // lblD3_1
            // 
            this.lblD3_1.AutoSize = true;
            this.lblD3_1.BackColor = System.Drawing.Color.Transparent;
            this.lblD3_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD3_1.Location = new System.Drawing.Point(6, 113);
            this.lblD3_1.Name = "lblD3_1";
            this.lblD3_1.Size = new System.Drawing.Size(247, 13);
            this.lblD3_1.TabIndex = 80;
            this.lblD3_1.Text = "1234567890123456789012345678901234567890";
            // 
            // lblD2_3
            // 
            this.lblD2_3.AutoSize = true;
            this.lblD2_3.BackColor = System.Drawing.Color.Transparent;
            this.lblD2_3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD2_3.Location = new System.Drawing.Point(6, 94);
            this.lblD2_3.Name = "lblD2_3";
            this.lblD2_3.Size = new System.Drawing.Size(247, 13);
            this.lblD2_3.TabIndex = 79;
            this.lblD2_3.Text = "1234567890123456789012345678901234567890";
            // 
            // lblD2_2
            // 
            this.lblD2_2.AutoSize = true;
            this.lblD2_2.BackColor = System.Drawing.Color.Transparent;
            this.lblD2_2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD2_2.Location = new System.Drawing.Point(6, 79);
            this.lblD2_2.Name = "lblD2_2";
            this.lblD2_2.Size = new System.Drawing.Size(247, 13);
            this.lblD2_2.TabIndex = 78;
            this.lblD2_2.Text = "1234567890123456789012345678901234567890";
            // 
            // lblD2_1
            // 
            this.lblD2_1.AutoSize = true;
            this.lblD2_1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD2_1.Location = new System.Drawing.Point(6, 64);
            this.lblD2_1.Name = "lblD2_1";
            this.lblD2_1.Size = new System.Drawing.Size(247, 13);
            this.lblD2_1.TabIndex = 77;
            this.lblD2_1.Text = "1234567890123456789012345678901234567890";
            // 
            // lblJ
            // 
            this.lblJ.AutoSize = true;
            this.lblJ.BackColor = System.Drawing.Color.Transparent;
            this.lblJ.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblJ.Location = new System.Drawing.Point(6, 47);
            this.lblJ.Name = "lblJ";
            this.lblJ.Size = new System.Drawing.Size(79, 13);
            this.lblJ.TabIndex = 76;
            this.lblJ.Text = "123456789012";
            // 
            // lblD1
            // 
            this.lblD1.AutoSize = true;
            this.lblD1.BackColor = System.Drawing.Color.Transparent;
            this.lblD1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblD1.Location = new System.Drawing.Point(6, 31);
            this.lblD1.Name = "lblD1";
            this.lblD1.Size = new System.Drawing.Size(157, 13);
            this.lblD1.TabIndex = 75;
            this.lblD1.Text = "1234567890123456789012345";
            // 
            // lblE
            // 
            this.lblE.AutoSize = true;
            this.lblE.BackColor = System.Drawing.Color.Transparent;
            this.lblE.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblE.Location = new System.Drawing.Point(6, 16);
            this.lblE.Name = "lblE";
            this.lblE.Size = new System.Drawing.Size(182, 13);
            this.lblE.TabIndex = 74;
            this.lblE.Text = "1234567890123456789012345";
            // 
            // RegistrationCardBack
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::EVR.ReadVehicleLicenseCardDemo.Properties.Resources.kentekenbewijs_ak_new;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.Controls.Add(this.pnleVRBack);
            this.DoubleBuffered = true;
            this.Name = "RegistrationCardBack";
            this.Size = new System.Drawing.Size(586, 370);
            this.Paint += new System.Windows.Forms.PaintEventHandler(this.RegistrationCardBack_Paint);
            this.pnleVRBack.ResumeLayout(false);
            this.pnleVRBack.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel pnleVRBack;
        private System.Windows.Forms.Label lblS2;
        private System.Windows.Forms.Label lblS1;
        private System.Windows.Forms.Label lblT;
        private System.Windows.Forms.Label lblG;
        private System.Windows.Forms.Label lblO2;
        private System.Windows.Forms.Label lblO1;
        private System.Windows.Forms.Label lblQ;
        private System.Windows.Forms.Label lblP3;
        private System.Windows.Forms.Label lblP2;
        private System.Windows.Forms.Label lblP1;
        private System.Windows.Forms.Label lblF3;
        private System.Windows.Forms.Label lblF2;
        private System.Windows.Forms.Label lblF1;
        private System.Windows.Forms.Label lblV9;
        private System.Windows.Forms.Label lblK;
        private System.Windows.Forms.Label lblR;
        private System.Windows.Forms.Label lblD3_2;
        private System.Windows.Forms.Label lblD3_1;
        private System.Windows.Forms.Label lblD2_3;
        private System.Windows.Forms.Label lblD2_2;
        private System.Windows.Forms.Label lblD2_1;
        private System.Windows.Forms.Label lblJ;
        private System.Windows.Forms.Label lblD1;
        private System.Windows.Forms.Label lblE;

    }
}
